apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: keycloak
  labels:
    app: keycloak
  annotations:
    kubernetes.io/description: "Keycloak realm configuration"
data:
  realm-export.json: |
    {
      "realm": "tennis",
      "enabled": true,
      "clients": [
        {
          "clientId": "frontend",
          "publicClient": true,
          "redirectUris": ["http://localhost:3000/*"]
        }
      ]
    }
